import React, { createContext, useContext, useState, useCallback } from 'react';
import type { ReactNode } from 'react';

export type TaskStatus = 'pending' | 'in-progress' | 'completed' | 'delayed';

export interface Task {
  id: string;
  title: string;
  department: 'IT' | 'Security' | 'Facilities' | 'HR';
  status: TaskStatus;
  assignee: string;
}

export interface Employee {
  id: string;
  name: string;
  role: string;
  status: 'hired' | 'active' | 'promoted' | 'terminated';
  department: string;
  stage: 'onboarding' | 'active' | 'offboarding';
  tasks: Task[];
}

export interface SystemLog {
  id: string;
  timestamp: string;
  message: string;
  type: 'info' | 'success' | 'warning' | 'error';
}

interface WorkflowContextType {
  employees: Employee[];
  logs: SystemLog[];
  activeView: string;
  setActiveView: (view: string) => void;
  triggerOnboarding: (name: string, role: string, department: string) => void;
  updateTaskStatus: (employeeId: string, taskId: string, status: TaskStatus) => void;
  addLog: (message: string, type: SystemLog['type']) => void;
  runSimulation: () => void;
}

const WorkflowContext = createContext<WorkflowContextType | undefined>(undefined);

export const WorkflowProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [logs, setLogs] = useState<SystemLog[]>([]);
  const [activeView, setActiveView] = useState('home');
  const [loading, setLoading] = useState(true);

  const API_BASE = 'http://localhost:3000';

  const fetchData = useCallback(async () => {
    try {
      const [empRes, logRes] = await Promise.all([
        fetch(`${API_BASE}/employees`),
        fetch(`${API_BASE}/logs?_sort=id&_order=desc&_limit=50`)
      ]);
      
      if (!empRes.ok || !logRes.ok) throw new Error('Backend server is not responding correctly.');

      const empData = await empRes.json();
      const logData = await logRes.json();
      
      setEmployees(empData);
      setLogs(logData);
    } catch (error) {
      console.error('Failed to connect to JSON-server:', error);
    } finally {
      setLoading(false);
    }
  }, []);

  React.useEffect(() => {
    fetchData();
  }, [fetchData]);

  const addLog = useCallback(async (message: string, type: SystemLog['type']) => {
    const newLog: SystemLog = { 
      id: Date.now().toString(), 
      timestamp: new Date().toLocaleTimeString(), 
      message, 
      type 
    };

    try {
      const res = await fetch(`${API_BASE}/logs`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(newLog)
      });
      if (res.ok) {
        setLogs(prev => [newLog, ...prev].slice(0, 50));
      }
    } catch (error) {
      console.error('Log sync failed:', error);
    }
  }, []);

  const triggerOnboarding = useCallback(async (name: string, role: string, department: string) => {
    const newTasks: Task[] = [
      { id: `T_IT_${Date.now()}`, title: 'Laptop Provisioning', department: 'IT', status: 'pending', assignee: 'IT Fleet' },
      { id: `T_IT2_${Date.now()}`, title: 'Email Account Setup', department: 'IT', status: 'pending', assignee: 'SysAdmin' },
      { id: `T_SEC_${Date.now()}`, title: 'Access Badge Creation', department: 'Security', status: 'pending', assignee: 'Security Desk' },
      { id: `T_FAC_${Date.now()}`, title: 'Desk Allocation', department: 'Facilities', status: 'pending', assignee: 'Ops Team' }
    ];

    const tempEmployee: Omit<Employee, 'id'> = {
      name,
      role,
      department,
      status: 'hired',
      stage: 'onboarding',
      tasks: newTasks
    };

    try {
      const res = await fetch(`${API_BASE}/employees`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(tempEmployee)
      });
      
      if (res.ok) {
        const savedEmployee = await res.json();
        // Use the ID generated by the server
        setEmployees(prev => [savedEmployee, ...prev]);
        addLog(`New Hire Detected: ${name} (${role})`, 'info');
        addLog(`Workflow Triggered: Onboarding flow for ${savedEmployee.id}`, 'success');
      }
    } catch (error) {
      console.error('Onboarding sync failed:', error);
    }
  }, [addLog]);

  const updateTaskStatus = useCallback(async (employeeId: string, taskId: string, status: TaskStatus) => {
    const employee = employees.find(e => e.id === employeeId);
    if (!employee) return;

    const updatedTasks = employee.tasks.map(t => t.id === taskId ? { ...t, status } : t);

    try {
      const res = await fetch(`${API_BASE}/employees/${employeeId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tasks: updatedTasks })
      });

      if (res.ok) {
        setEmployees(prev => prev.map(emp => {
          if (emp.id === employeeId) {
             return { ...emp, tasks: updatedTasks };
          }
          return emp;
        }));
        addLog(`Task Updated: ${taskId} set to ${status}`, 'info');
      }
    } catch (error) {
      console.error('Task status sync failed:', error);
    }
  }, [employees, addLog]);

  const runSimulation = useCallback(() => {
    addLog('Manual Simulation Triggered', 'warning');
    
    setTimeout(() => {
      triggerOnboarding('Simulation User', 'Automated Agent', 'System');
    }, 500);

    setTimeout(() => {
      addLog('Active Directory: Provisions started for Simulation User', 'info');
    }, 2000);

    setTimeout(() => {
      addLog('Slack: Notification sent to #general', 'success');
    }, 3500);
  }, [addLog, triggerOnboarding]);

  if (loading) {
     return (
       <div style={{ height: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#0f172a', color: 'white' }}>
          <div style={{ textAlign: 'center' }}>
             <div style={{ width: '40px', height: '40px', border: '3px solid rgba(255,255,255,0.1)', borderTopColor: '#6366f1', borderRadius: '50%', animation: 'spin 1s linear infinite', margin: '0 auto 16px' }} />
             <p style={{ fontSize: '14px', color: '#94a3b8' }}>Syncing with Enterprise Backend...</p>
          </div>
          <style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style>
       </div>
     );
  }

  return (
    <WorkflowContext.Provider value={{
      employees,
      logs,
      activeView,
      setActiveView,
      triggerOnboarding,
      updateTaskStatus,
      addLog,
      runSimulation
    }}>
      {children}
    </WorkflowContext.Provider>
  );
};

export const useWorkflow = () => {
  const context = useContext(WorkflowContext);
  if (!context) throw new Error('useWorkflow must be used within a WorkflowProvider');
  return context;
};
